#==============================================================================#
# Amethy                                             ©2022 Wany (sung@wany.io) #
#                                                       https://amethy.wany.io #
#==============================================================================#

# Amethy 플러그인 설정 파일입니다.
# 변경 및 저장 후 amethy reload 명령어를 사용하여 적용하십시오.

#==============================================================================#
updater:
  channel: 'dev'
  auto: true
debug: false
#==============================================================================#
