name: Amethy
version: 1.18-dev
main: io.wany.amethy.Amethy

description: Amethy
author: Wany
website: https://amethy.wany.io

api-version: 1.18
softdepend: [CoreProtect, Cucumbery, Vault]
loadbefore:
  - CoreProtect
  - Cucumbery
  - Essentials
  - HolographicDisplays
  - LuckPerms
  - mcMMO
  - NoteBlockAPI
  - PlugMan
  - ProtocolLib
  - QuickShop
  - Vault
  - VoxelSniper
  - WorldEdit
  - WorldGuard
