name: Amethy
version: 1.18-dev
main: io.wany.amethy.Amethy

description: Amethy
author: Wany
website: https://amethy.wany.io

api-version: 1.18
softdepend: [CoreProtect, Cucumbery, Vault]
loadbefore:
  - CoreProtect
  - Cucumbery
  - Essentials
  - HolographicDisplays
  - LuckPerms
  - mcMMO
  - NoteBlockAPI
  - PlugMan
  - ProtocolLib
  - QuickShop
  - Vault
  - VoxelSniper
  - WorldEdit
  - WorldGuard

commands:
  amethy:
    permission: amethy.command.amethy
    aliases: [a, amethy, c]

  wandedit:
    permission: amethy.command.wand.edit
    aliases: [awand, we, wand, ww, //]

  wandbrush:
    permission: amethy.command.wand.brush
    aliases: [abrush, wb, brush]

  portal:
    permission: amethy.command.portal
    aliases: [aportal]

  menu:
    permission: amethy.command.menu
    aliases: [amenu, apsb, 메뉴, ㅡ두ㅕ]

  throw:
    permission: amethy.command.throw

  troll:
    permission: amethy.command.troll

  bungeeteleport:
    permission: amethy.command.bungeeteleport
    aliases: [btp, gtp, tpb]

  list:
    description: 'Show list of online players'
    usage: '/<command>'
    permission: amethy.command.list
    aliases: [alist, ls]

  exit:
    description: 'Exit the game'
    usage: '/<command>'
    permission: minecraft.command.exit
    aliases: [quit, 나가기, 겜접, gg]

  drop:
    description: 'Drop current hand item'
    usage: '/<command> [true|false]'
    permission: minecraft.command.drop

  lid:
    description: 'Change block state of lidded block'
    usage: '/<command> [open|close|toggle] [x] [y] [z] [world]'
    permission: minecraft.command.lid

  toggledownfall:
    description: 'Toggle downfall'
    usage: '/<command>'
    permission: minecraft.command.toggledownfall

  closeinventory:
    description: "Close player's opened inventory"
    usage: '/<command> [player]'
    permission: minecraft.command.closeinventory
    aliases: [cci]
